package EletroStore.entity;

// Generated Dec 23, 2013 6:20:06 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Brand generated by hbm2java
 */
@Entity
@Table(name = "brand", catalog = "bestbuy")
public class Brand implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5333111958696228750L;
	private Integer brandid;
	private String brandname;
	private String brandimage;
	private Set<Products> productses = new HashSet<Products>(0);

	public Brand() {
	}

	public Brand(String brandname) {
		this.brandname = brandname;
	}

	public Brand(String brandname, String brandimage, Set<Products> productses) {
		this.brandname = brandname;
		this.brandimage = brandimage;
		this.productses = productses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "brandid", unique = true, nullable = false)
	public Integer getBrandid() {
		return this.brandid;
	}

	public void setBrandid(Integer brandid) {
		this.brandid = brandid;
	}

	@Column(name = "brandname", nullable = false, length = 45)
	public String getBrandname() {
		return this.brandname;
	}

	public void setBrandname(String brandname) {
		this.brandname = brandname;
	}

	@Column(name = "brandimage", length = 45)
	public String getBrandimage() {
		return this.brandimage;
	}

	public void setBrandimage(String brandimage) {
		this.brandimage = brandimage;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "brand")
	public Set<Products> getProductses() {
		return this.productses;
	}

	public void setProductses(Set<Products> productses) {
		this.productses = productses;
	}

}
