package EletroStore.entity;

// Generated Dec 23, 2013 6:20:06 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Deals generated by hbm2java
 */
@Entity
@Table(name = "deals", catalog = "bestbuy")
public class Deals implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8461404645867982346L;
	private Integer dealid;
	private String dealname;
	private String dealimage;
	private String dealdescription;
	private Set<Products> productses = new HashSet<Products>(0);

	public Deals() {
	}

	public Deals(String dealname, String dealimage, String dealdescription,
			Set<Products> productses) {
		this.dealname = dealname;
		this.dealimage = dealimage;
		this.dealdescription = dealdescription;
		this.productses = productses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "dealid", unique = true, nullable = false)
	public Integer getDealid() {
		return this.dealid;
	}

	public void setDealid(Integer dealid) {
		this.dealid = dealid;
	}

	@Column(name = "dealname", length = 45)
	public String getDealname() {
		return this.dealname;
	}

	public void setDealname(String dealname) {
		this.dealname = dealname;
	}

	@Column(name = "dealimage", length = 45)
	public String getDealimage() {
		return this.dealimage;
	}

	public void setDealimage(String dealimage) {
		this.dealimage = dealimage;
	}

	@Column(name = "dealdescription", length = 100)
	public String getDealdescription() {
		return this.dealdescription;
	}

	public void setDealdescription(String dealdescription) {
		this.dealdescription = dealdescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deals")
	public Set<Products> getProductses() {
		return this.productses;
	}

	public void setProductses(Set<Products> productses) {
		this.productses = productses;
	}

}
