package EletroStore.entity;

// Generated Dec 31, 2013 1:56:48 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Orderstatus generated by hbm2java
 */
@Entity
@Table(name = "orderstatus", catalog = "bestbuy")
public class Orderstatus implements java.io.Serializable {

	private Integer orderstatusid;
	private String orderstatusname;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public Orderstatus() {
	}

	public Orderstatus(String orderstatusname, Set<Orders> orderses) {
		this.orderstatusname = orderstatusname;
		this.orderses = orderses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "orderstatusid", unique = true, nullable = false)
	public Integer getOrderstatusid() {
		return this.orderstatusid;
	}

	public void setOrderstatusid(Integer orderstatusid) {
		this.orderstatusid = orderstatusid;
	}

	@Column(name = "orderstatusname", length = 45)
	public String getOrderstatusname() {
		return this.orderstatusname;
	}

	public void setOrderstatusname(String orderstatusname) {
		this.orderstatusname = orderstatusname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "orderstatus")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

}
