package EletroStore.entity;

// Generated Dec 23, 2013 6:20:06 AM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Productcatalog generated by hbm2java
 */
@Entity
@Table(name = "productcatalog", catalog = "bestbuy")
public class Productcatalog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7877348210474941356L;
	private Integer catalogid;
	private String catalogimage;
	private String catalogname;
	private Set<Products> productses = new HashSet<Products>(0);

	public Productcatalog() {
	}

	public Productcatalog(String catalogname) {
		this.catalogname = catalogname;
	}

	public Productcatalog(String catalogimage, String catalogname,
			Set<Products> productses) {
		this.catalogimage = catalogimage;
		this.catalogname = catalogname;
		this.productses = productses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "catalogid", unique = true, nullable = false)
	public Integer getCatalogid() {
		return this.catalogid;
	}

	public void setCatalogid(Integer catalogid) {
		this.catalogid = catalogid;
	}

	@Column(name = "catalogimage", length = 100)
	public String getCatalogimage() {
		return this.catalogimage;
	}

	public void setCatalogimage(String catalogimage) {
		this.catalogimage = catalogimage;
	}

	@Column(name = "catalogname", nullable = false, length = 100)
	public String getCatalogname() {
		return this.catalogname;
	}

	public void setCatalogname(String catalogname) {
		this.catalogname = catalogname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productcatalog")
	public Set<Products> getProductses() {
		return this.productses;
	}

	public void setProductses(Set<Products> productses) {
		this.productses = productses;
	}

}
