package EletroStore.entity;

// Generated Dec 31, 2013 1:56:48 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Productcatalog generated by hbm2java
 */
@Entity
@Table(name = "productcatalog", catalog = "bestbuy")
public class Productcatalog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6232246381083500315L;
	private Integer catalogid;
	private String catalogimage;
	private String catalogname;
	private Set<Product> products = new HashSet<Product>(0);

	public Productcatalog() {
	}

	public Productcatalog(String catalogname) {
		this.catalogname = catalogname;
	}

	public Productcatalog(String catalogimage, String catalogname,
			Set<Product> products) {
		this.catalogimage = catalogimage;
		this.catalogname = catalogname;
		this.products = products;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "catalogid", unique = true, nullable = false)
	public Integer getCatalogid() {
		return this.catalogid;
	}

	public void setCatalogid(Integer catalogid) {
		this.catalogid = catalogid;
	}

	@Column(name = "catalogimage", length = 100)
	public String getCatalogimage() {
		return this.catalogimage;
	}

	public void setCatalogimage(String catalogimage) {
		this.catalogimage = catalogimage;
	}

	@Column(name = "catalogname", nullable = false, length = 100)
	public String getCatalogname() {
		return this.catalogname;
	}

	public void setCatalogname(String catalogname) {
		this.catalogname = catalogname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productcatalog")
	public Set<Product> getProducts() {
		return this.products;
	}

	public void setProducts(Set<Product> products) {
		this.products = products;
	}

}
