package EletroStore.entity;

// Generated Dec 21, 2013 4:07:42 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Uservoteproduct generated by hbm2java
 */
@Entity
@Table(name = "uservoteproduct", catalog = "bestbuy")
public class Uservoteproduct implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2224512344276021203L;
	private Integer voteid;
	private User user;
	private Products products;
	private Integer star;
	private Date datetime;

	public Uservoteproduct() {
	}

	public Uservoteproduct(User user, Products products, Integer star,
			Date datetime) {
		this.user = user;
		this.products = products;
		this.star = star;
		this.datetime = datetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "voteid", unique = true, nullable = false)
	public Integer getVoteid() {
		return this.voteid;
	}

	public void setVoteid(Integer voteid) {
		this.voteid = voteid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "userid")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productid")
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@Column(name = "star")
	public Integer getStar() {
		return this.star;
	}

	public void setStar(Integer star) {
		this.star = star;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datetime", length = 19)
	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

}
