package EletroStore.entity;

// Generated Dec 31, 2013 1:56:48 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Wishlist generated by hbm2java
 */
@Entity
@Table(name = "wishlist", catalog = "bestbuy")
public class Wishlist implements java.io.Serializable {

	private Integer wishlistid;
	private User user;
	private Product product;
	private Date dateadd;

	public Wishlist() {
	}

	public Wishlist(User user, Product product, Date dateadd) {
		this.user = user;
		this.product = product;
		this.dateadd = dateadd;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "wishlistid", unique = true, nullable = false)
	public Integer getWishlistid() {
		return this.wishlistid;
	}

	public void setWishlistid(Integer wishlistid) {
		this.wishlistid = wishlistid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "memberid")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productid")
	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateadd", length = 19)
	public Date getDateadd() {
		return this.dateadd;
	}

	public void setDateadd(Date dateadd) {
		this.dateadd = dateadd;
	}

}
