package EletroStore.entity;

// Generated Dec 21, 2013 4:07:42 AM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Wishlist generated by hbm2java
 */
@Entity
@Table(name = "wishlist", catalog = "bestbuy")
public class Wishlist implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2960470869889981675L;
	private Integer wishlistid;
	private User user;
	private Products products;
	private Date dateadd;

	public Wishlist() {
	}

	public Wishlist(User user, Products products, Date dateadd) {
		this.user = user;
		this.products = products;
		this.dateadd = dateadd;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "wishlistid", unique = true, nullable = false)
	public Integer getWishlistid() {
		return this.wishlistid;
	}

	public void setWishlistid(Integer wishlistid) {
		this.wishlistid = wishlistid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "memberid")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "productid")
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateadd", length = 19)
	public Date getDateadd() {
		return this.dateadd;
	}

	public void setDateadd(Date dateadd) {
		this.dateadd = dateadd;
	}

}
